---
# tasks file for database

  - name: Make sure local temp directory exists
    local_action: file path="/tmp/{{ ssh_user }}" state=directory

  - include: db_dump.yml
    when: not from_cache|bool

  - name: Check local database name
    local_action: shell docker-compose run --rm -T app ./flow configuration:show --type Settings --path TYPO3.Flow.persistence.backendOptions | grep 'dbname' | cut -d ' ' -f2
                  chdir="{{ local_path }}"
    register: local_db_name

  - name: Drop local database
    local_action: shell docker-compose run --rm db mysqladmin -h db -u prettygreenplants -pprettygreenplants drop {{ local_db_name.stdout }} -f
                  chdir="{{ local_path }}"

  - name: Re-create local database
    local_action: shell docker-compose run --rm db mysqladmin -h db -u prettygreenplants -pprettygreenplants create {{ local_db_name.stdout }} --default-character-set=utf8
                  chdir="{{ local_path }}"

  - name: Restore local database from remote dump
    local_action: shell docker-compose run --rm db mysql -h db -u prettygreenplants -pprettygreenplants {{ local_db_name.stdout }} < /tmp/{{ ssh_user }}/db_dump.sql
                  chdir="{{ local_path }}"
