backup:
  image: confirm/mysql-backup:latest
  environment:
    BACKUP_GID: 1001
    BACKUP_UID: 1001
  external_links:
    - prettygreenplants_db_1:db
  volumes:
    - './backup/db:/backup'

restore:
  image: confirm/mysql-backup:latest
  environment:
    BACKUP_GID: 1001
    BACKUP_UID: 1001
    MODE: RESTORE
  external_links:
    - prettygreenplants_db_1:db
  volumes:
    - './backup/db:/backup'
