app:
  image: prettygreenplants/app:latest
  volumes:
  - './neos:/var/www/prettygreenplants'
  - './scripts/cleanup.sh:/cleanup.sh:ro'
  links:
  - db
  - redis
  ports:
  - '8080:9000'
  environment:
    FLOW_CONTEXT: 'Production'

# TODO: Move to RDS
db:
  image: mariadb:10.1
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  volumes:
  - '/var/lib/mysql'
  environment:
    MYSQL_ROOT_PASSWORD: 'root'
    MYSQL_USER: 'prettygreenplants'
    MYSQL_PASSWORD: 'prettygreenplants'
    MYSQL_DATABASE: 'prettygreenplants'

redis:
  image: redis:alpine

web:
  image: prettygreenplants/nginx:latest
  ports:
  - '80:80'
  - '443:443'
  volumes:
  - './neos:/var/www/prettygreenplants'
  - '/etc/letsencrypt:/etc/letsencrypt'
  net: 'host'
  environment:
  - NGINX_HOST=prettygreenplants.com
  - USE_SELF_SIGNED_CERTIFICATE=False
