version: '3'

services:
  app:
    build: 'docker/app'
    volumes:
    - './neos:/var/www/prettygreenplants'
    - './scripts/cleanup.sh:/cleanup.sh:ro'
    links:
    - db
    - redis
    ports:
    - '8080:9000'
    env_file: .env

  db:
    image: mariadb:10.1
    container_name: prettygreenplants_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
    - '/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'prettygreenplants'
      MYSQL_PASSWORD: 'prettygreenplants'
      MYSQL_DATABASE: 'prettygreenplants'
    # ports:
    # - '3306:3306'

  db_backup:
    build: ./docker/db-backup
    environment:
      MYSQL_CONTAINER_NAME: prettygreenplants_db
      MYSQL_DATABASE: 'prettygreenplants'
      MYSQL_ROOT_PASSWORD: 'root'
      BACKUP_GID: 1001
      BACKUP_UID: 1001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backup/db:/opt/mysql/backup
    command: crond -f -d 8

  redis:
    image: redis:alpine

  web:
    build: 'docker/web'
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - './neos:/var/www/prettygreenplants'
    env_file: .env
    network_mode: 'host'
