db:
  image: 'mariadb:10.1'
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  volumes:
    - /var/lib/mysql
    - .:/var/www
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=prettygreenplants
    - MYSQL_PASSWORD=prettygreenplants
    - MYSQL_DATABASE=prettygreenplants
#  ports:
#    - "3306:3306"

# App container which provides the php environment
app:
  # For development of the image comment out the 'image' line and replace with the next line
  build: 'docker/app'
  #image: 'visay/prettygreenplants_app:latest'
  volumes:
    - .:/var/www
  links:
    - db
  environment:
    - WWW_USER_ID=1001
#    - WWW_USER=prettygreenplants
#    - FLOW_CONTEXT=Production

web:
  build: 'docker/web'
#  image: 'visay/prettygreenplants_nginx:latest'
  ports:
    - "80:80"
  volumes:
    - .:/var/www
  links:
    - app
#  environment:
#    - NGINX_HOST=prettygreenplants.local
