version: '3'

services:

  app:
    image: prettygreenplants/app:latest
    volumes:
    - './neos:/var/www/prettygreenplants'
    - './scripts/cleanup.sh:/cleanup.sh:ro'
    links:
    - db
    - redis
    ports:
    - '8080:9000'
    env_file: .env

  # TODO: Move to RDS
  db:
    image: mariadb:10.1
    container_name: prettygreenplants_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
    - '/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'prettygreenplants'
      MYSQL_PASSWORD: 'prettygreenplants'
      MYSQL_DATABASE: 'prettygreenplants'

  db_backup:
    image: prettygreenplants/scheduler:latest
    environment:
      MYSQL_CONTAINER_NAME: prettygreenplants_db
      MYSQL_DATABASE: 'prettygreenplants'
      MYSQL_ROOT_PASSWORD: 'root'
      # TODO: This is manually hard-coded to align with server for now
      BACKUP_GID: 1261
      BACKUP_UID: 1261
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/www/backup/prettygreenplants/db:/opt/mysql/backup
    command: crond -f -d 8
    restart: always

  redis:
    image: redis:alpine

  web:
    image: prettygreenplants/nginx:latest
    ports:
    - '80:80'
    - '443:443'
    volumes:
    - './neos:/var/www/prettygreenplants'
    - '/etc/letsencrypt:/etc/letsencrypt'
    env_file: .env
    network_mode: 'host'
