<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170610213808 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE prettygreenplants_shop_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, parentcategory VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_68E686C74C8CFA (parentcategory), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prettygreenplants_shop_domain_model_product (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, cost INT NOT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_12D3E53A64C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE prettygreenplants_shop_domain_model_category ADD CONSTRAINT FK_68E686C74C8CFA FOREIGN KEY (parentcategory) REFERENCES prettygreenplants_shop_domain_model_category (persistence_object_identifier)');
        $this->addSql('ALTER TABLE prettygreenplants_shop_domain_model_product ADD CONSTRAINT FK_12D3E53A64C19C1 FOREIGN KEY (category) REFERENCES prettygreenplants_shop_domain_model_category (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE prettygreenplants_shop_domain_model_category DROP FOREIGN KEY FK_68E686C74C8CFA');
        $this->addSql('ALTER TABLE prettygreenplants_shop_domain_model_product DROP FOREIGN KEY FK_12D3E53A64C19C1');
        $this->addSql('DROP TABLE prettygreenplants_shop_domain_model_category');
        $this->addSql('DROP TABLE prettygreenplants_shop_domain_model_product');
    }
}
