---
# tasks file for ansible/roles/db

- name: Create database user
  debug:
    msg='User created manually through cpanel and set in {{ database_login_path }}/{{ inventory_hostname }}'

- name: Check if datbase login file exists
  stat:
    path='{{ database_login_path }}/{{ inventory_hostname }}'
  register: my_cnf

- name: Fail if database login file does not exist
  fail:
    msg='Please setup db connection at {{ database_login_path }}/{{ inventory_hostname }}'
  when: my_cnf.stat.exists == False

- name: Create database
  shell: >
    mysql --defaults-extra-file='{{ database_login_path }}/{{ inventory_hostname }}' -e 'CREATE DATABASE IF NOT EXISTS {{ database_name }} DEFAULT CHARSET utf8 COLLATE utf8_unicode_ci';
