---

galaxy_info:
  author: Visay Keo
  description: Sync resources from remote machine to local
  company: Pretty Green Plants
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - xenial
dependencies: []
