---

app_root: '/var/www/{{ project_name }}'
letsencrypt_dir: '/etc/letsencrypt'
www_user: 'ubuntu'
www_group: 'ubuntu'

project_context: 'Production'
composer_dev_flag: 'yes'
release_version: 'master'

temp_files:
  - 'Configuration/PackageStates.php'
  - 'Data/Logs/Exceptions'
  - 'Data/Logs/I18n_Development.log'
  - 'Data/Logs/Security_Development.log'
  - 'Data/Logs/System_Development.log'
  - 'Data/Temporary'
  - 'Web/_Resources'

google_analytic_app_name: '{{ google_analytic_app_name_vault }}'
google_analytic_client_id: '{{ google_analytic_client_id_vault }}'
google_analytic_client_secret: '{{ google_analytic_client_secret_vault }}'
google_analytic_api_key: '{{ google_analytic_api_key_vault }}'
google_analytic_tracking_id: '{{ google_analytic_tracking_id_vault }}'
google_analytic_profile_id: '{{ google_analytic_profile_id_vault }}'
