#
# Production Context Settings used for aws docker
#
TYPO3:
  Flow:
    persistence:
      backendOptions:
        host: db
        user: prettygreenplants
        password: prettygreenplants
        dbname: prettygreenplants
