---
# tasks file for common

- name: Display warning to manually manage system upgrade
  debug:
    msg: 'Please manually run apt-get upgrade to apply updates'

- name: Display info to setup live patch
  debug:
    msg: 'Please manually activate Canonical Livepatch at https://ubuntu.com/livepatch if kernel support'

- name: Set timezone to Phnom Penh
  timezone:
    name: Asia/Phnom_Penh

- name: Update package caches
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Add repo for php
  apt_repository:
    repo: 'ppa:ondrej/php'
    filename: php

- name: Add repo for letsencrypt
  apt_repository:
    repo: 'ppa:certbot/certbot'
    filename: letsencrypt

- name: Install packages
  apt:
    name: '{{ common_packages }}'
    force_apt_get: yes

- name: Download composer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: /tmp/installer

- name: Install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Make composer executable
  file:
    path: /usr/local/bin/composer
    mode: 'a+x'
    state: file

- name: Update composer to latest version
  composer:
    command: self-update
    working_dir: /usr/local/bin

- name: Fix permission for composer cache directory
  file:
    path: '/home/{{ host_user }}/.composer'
    state: directory
    owner: '{{ host_user }}'
    group: '{{ host_group }}'
    recurse: yes

- name: Check if letsencrypt certificate exists
  stat:
    path: /etc/letsencrypt/live/prettygreenplants.com/fullchain.pem
  register: letsencrypt_certs

- import_tasks: letsencrypt.yml
  when: letsencrypt_certs.stat.exists == False

- name: Generate ssl certificate
  shell: /usr/bin/letsencrypt certonly --keep --expand --agree-tos -m keo@visay.info -n --webroot -w /etc/letsencrypt/prettygreenplants -d prettygreenplants.com -d www.prettygreenplants.com

#- name: Install cronjob for generating ssl certificate
#  cron:
#    name: letsencrypt
#    day: 1-5
#    hour: 1
#    minute: 0
#    job: /usr/bin/letsencrypt certonly --keep --expand --agree-tos -m keo@visay.info -n --webroot -w /etc/letsencrypt/prettygreenplants -d prettygreenplants.com

# TODO need to add --hook to reload the container to take new certificate
- name: Verify that cron job for letsencrypt exists automatically
  debug:
    msg: 'Check if /etc/cron.d/certbot is auto created and content looks good'
