---
# tasks file for common

- name: Update package caches
  apt: update_cache=yes

- name: Install packages
  apt: name='{{ item }}'
  with_items:
    - git
    - php7.0-cli
    - php7.0-mbstring
    - php7.0-xml
    - php7.0-zip

- name: Download composer
  get_url: url=https://getcomposer.org/installer
           dest=/tmp/installer

- name: Install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Make composer executable
  file: path=/usr/local/bin/composer
        mode=a+x
        state=file

- name: Update composer to latest version
  composer: command=self-update
            working_dir=/usr/local/bin

- name: Fix permission for composer cache directory
  file: path=/home/{{ www_user }}/.composer
        state=directory
        owner={{ www_user }}
        group={{ www_group }}
        recurse=yes
