---
# tasks file for common

- name: Set timezone to Phnom Penh
  timezone:
    name: Asia/Phnom_Penh

- name: Update package caches
  apt:
    update_cache: yes

- name: Add repo for letsencrypt
  apt_repository:
    repo: 'ppa:certbot/certbot'
    filename: letsencrypt

- name: Install packages
  apt:
    name: '{{ item }}'
  with_items: '{{ common_packages }}'

- name: Download composer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: /tmp/installer

- name: Install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Make composer executable
  file:
    path: /usr/local/bin/composer
    mode: 'a+x'
    state: file

- name: Update composer to latest version
  composer:
    command: self-update
    working_dir: /usr/local/bin

- name: Fix permission for composer cache directory
  file:
    path: '/home/{{ www_user }}/.composer'
    state: directory
    owner: '{{ www_user }}'
    group: '{{ www_group }}'
    recurse: yes

- name: Create directory for letsencrypt
  file:
    path: '{{ letsencrypt_dir }}/{{ project_name }}'
    state: directory

- name: Generate ssl certificate
  shell: /usr/bin/letsencrypt certonly --keep --expand --agree-tos -m keo@visay.info -n --webroot -w /etc/letsencrypt/prettygreenplants -d prettygreenplants.com

- name: Install cronjob for generating ssl certificate
  cron:
    name: letsencrypt
    day: 1-5
    hour: 1
    minute: 0
    job: /usr/bin/letsencrypt certonly --keep --expand --agree-tos -m keo@visay.info -n --webroot -w /etc/letsencrypt/prettygreenplants -d prettygreenplants.com
