---

galaxy_info:
  author: Visay Keo
  description: App role for installing project to aws cloud with docker.
  company: Pretty Green Plants
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  categories:
    - packaging
dependencies: []
