---

- name: Make sure backup directory exists
  file:
    path: '{{ backup_path }}/{{ item }}'
    owner: '{{ host_user }}'
    group: '{{ host_group }}'
    recurse: yes
    state: directory
  with_items:
    - db
    - files
    - scripts
  become: True

- name: Create file backup script
  template:
    src: backup_files.sh.j2
    dest: '{{ backup_path }}/scripts/backup_files.sh'
    mode: 0755

- name: Install cronjob for daily file backup
  cron:
    name: prettygreenplants_daily_file_backup
    hour: '23'
    minute: '30'
    job: '{{ backup_path }}/scripts/backup_files.sh'

# - name: Install cronjob for daily backup sync to s3
#   cron:
#     name: daily_backup_sync
#     hour: '0'
#     minute: '30'
#     job: '/usr/local/bin/aws s3 sync /var/www/backup/{{ project_name }}/ s3://pgp-website-backup/ --delete --sse --storage-class ONEZONE_IA --quiet'

- name: Create rotate script on the server
  template:
    src: 'rotate.sh.j2'
    dest: '{{ backup_path }}/scripts/rotate.sh'
    mode: 0755

- name: Install cronjob for monthly rotate
  cron:
    name: prettygreenplants_monthly_rotate
    day: '28'
    hour: '1'
    minute: '0'
    job: '{{ backup_path }}/scripts/rotate.sh'

# - name: Install cronjob for daily cleanup docker images
#   cron:
#     name: daily_docker_image_cleanup
#     hour: '1'
#     minute: '30'
#     job: 'docker rmi $(docker images -f "dangling=true" -q)'
