---

- name: Make sure backup directory exists
  file:
    path: '/var/www/backup/{{ project_name }}/{{ item }}'
    owner: '{{ host_user }}'
    group: '{{ host_group }}'
    recurse: yes
    state: directory
  with_items:
    - db
    - files
  become: True

- name: Install cronjob for daily db backup
  cron:
    name: daily_db_backup
    hour: '23'
    minute: '0'
    job: '/usr/local/bin/docker-compose -f {{ app_root }}/docker-compose-maintainance-prod.yml run --rm backup'

- name: Create file backup script
  template:
    src: backup_files.sh.j2
    dest: /var/www/backup/backup_files.sh
    mode: 0755

- name: Install cronjob for daily file backup
  cron:
    name: daily_file_backup
    hour: '23'
    minute: '30'
    job: '/var/www/backup/backup_files.sh'

- name: Install cronjob for daily backup sync to s3
  cron:
    name: daily_backup_sync
    hour: '0'
    minute: '30'
    job: '/usr/local/bin/aws s3 sync /var/www/backup/{{ project_name }}/ s3://pgp2020-website-backup/ --delete --sse --storage-class ONEZONE_IA --quiet'

- name: Create rotate script on the server
  template:
    src: 'rotate.sh.j2'
    dest: '/var/www/backup/rotate.sh'
    mode: 0755

- name: Install cronjob for monthly rotate
  cron:
    name: monthly_rotate
    day: '28'
    hour: '1'
    minute: '0'
    job: '/var/www/backup/rotate.sh'
