---

app_root: '/var/www/{{ project_name }}'
www_user: 'ubuntu'
www_group: 'ubuntu'

project_context: 'Production'
composer_dev_flag: 'yes'
release_version: 'stable'

temp_files:
  - 'Configuration/PackageStates.php'
  - 'Data/Logs/Exceptions'
  - 'Data/Logs/I18n_Development.log'
  - 'Data/Logs/Security_Development.log'
  - 'Data/Logs/System_Development.log'
  - 'Data/Temporary'
  - 'Web/_Resources'
