## Site Settings
Sokly:
  PrettyGreenPlants:
    socialMedia:
      email: 'info@prettygreenplants.com'
      facebook: 'https://www.facebook.com/prettygreenplants'
    # TODO: Move copyrights text to language file
    copyrights: 'All Rights Reserved, PrettyGreenPlants.com'

## Overwrite Global Settings
Neos:
  Neos:
    userInterface:
      backendLoginForm:
        backgroundImage: 'resource://Sokly.PrettyGreenPlants/Public/img/wallpaper.jpg'
