---
# tasks file for docker

- name: Install packages
  apt:
    name: '{{ item }}'
  with_items: '{{ docker_packages }}'

- name: Add Docker’s official GPG key
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    filename: docker

- name: Install stable version
  apt:
    name: docker-ce=5:18.09.0~3-0~ubuntu-bionic

- name: Install docker compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.11.2/docker-compose-Linux-x86_64'
    dest: /usr/local/bin/docker-compose
    checksum: 'sha256:8d55adce12461c9f2abd907da1138b3e925919212611a54c94c4794ab0a975fc'
    mode: 'u+x,g+x,o+x'

- name: Check if the user is in docker group
  shell: 'groups {{ www_user }} | grep docker'
  register: docker_status
  ignore_errors: true

- name: Add current user to docker group
  shell: 'gpasswd -a {{ www_user }} docker'
  when: docker_status.failed

- name: Server restart needed
  fail:
    msg: 'Please reboot the server so Docker can run as {{ www_user }} user.'
  when: docker_status.failed
