---

- hosts: all

  roles:
    - role: common
      become: True
      tags: packages
    - role: docker
      become: True
      tags: packages
    - role: app
      tags: app
    - role: syncontent
      delegate_to: localhost
      tags: syncontent
