---

- hosts: staging
  roles:
    - role: app
      tags: deploy
    - role: backup
      tags: deploy
    - role: syncontent
      delegate_to: localhost
      tags: syncontent

- hosts: live
  roles:
    - role: common
      become: True
      tags: deploy
    - role: docker
      become: True
      tags: deploy
    - role: aws-cli
      become: True
      tags: deploy
    - role: app
      tags: deploy
    - role: backup
      tags: deploy
    - role: syncontent
      delegate_to: localhost
      tags: syncontent
