---
# tasks file for flow cleanup

  - name: Remove PackageStates.php and temp caches directory
    local_action: shell rm -rf Configuration/PackageStates.php Data/Temporary
                  chdir="{{ local_path }}"

  - name: Execute neccessary flow commands
    local_action: shell docker-compose run --rm app ./flow {{ item }}
                  chdir="{{ local_path }}"
    with_items:
      - flow:cache:flush --force
      - database:setcharset
      - doctrine:migrate
      - resource:clean
      - resource:publish
      - media:clearthumbnails
      - media:renderthumbnails
      - cache:warmup
