#
# Development Context Settings used for local docker
#
Sokly:
  PrettyGreenPlants:
    toggleBeta: true

TYPO3:
  Flow:
    persistence:
      backendOptions:
        host: db
        user: root
        password: root
        dbname: dockerflow
